---
- name: Authenticate with vROps and Check vROps Status
  hosts: localhost

  tasks:

    - name: Authenticate with vROps
      uri:
        url: "https://vrealizeops.ariel.lab/suite-api/api/auth/token/acquire"
        method: POST
        body_format: json
        body:
          username: "admin"
          password: "VMware1!"
        validate_certs: no
      register: auth_response

    - name: Fail if authentication failed
      fail:
        msg: "Authentication with vROps failed: {{ auth_response }}"
      when: auth_response.status != 200

    - name: Debug auth_response
      debug:
        msg: "The auth_response json is {{auth_response}}"

    - name: Set auth token as fact
      set_fact:
        auth_token: "{{ auth_response.json.token }}"

    - name: Get vROps status
      uri:
        url: "https://vrealizeops.ariel.lab/suite-api/api/resources"
        method: GET
        headers:
          Authorization: "OpsToken {{ auth_token }}"
          Content-Type: "application/json"
        validate_certs: no
      register: vrops_response

    - name: Display vROps status
      debug:
        msg: "vROps response: {{ vrops_response.json }}"
